ground_truth:
  fauna: data/summaries/authors/fauna_scoring_ground_truth.txt
  grazing: data/summaries/authors/grazing_scoring_ground_truth.txt
  milk_consumption: data/summaries/authors/milk_scoring_ground_truth.txt

modeler_ground_truth:
  milk_consumption: data/summaries/modelers/milk_modeler_ground_truth.txt

gpt5.2_short_ground_truth:
  fauna: data/summaries/gpt5.2/fauna_gpt5.2_short_ground_truth.txt
  grazing: data/summaries/gpt5.2/grazing_gpt5.2_short_ground_truth.txt
  milk_consumption: data/summaries/gpt5.2/milk_gpt5.2_short_ground_truth.txt

gpt5.2_long_ground_truth:
  fauna: data/summaries/gpt5.2/fauna_gpt5.2_long_ground_truth.txt
  grazing: data/summaries/gpt5.2/grazing_gpt5.2_long_ground_truth.txt
  milk_consumption: data/summaries/gpt5.2/milk_gpt5.2_long_ground_truth.txt

qualitative_example_text_dir: configs/prompt_assets/Evaluation/Qualitative Assessment using LLMs/Examples/Text
human_reference_dir: data/human_reference
