context_prompt: |
  Your goal is to explain an agent-based model.
  Your explanation must include the context of the model, its goals, and key parameters.
  For each parameter, include the range of values (if provided) and the value that we have set.
  Do not write any summary or conclusion.
  {parameters}

  The context and goals of the model are as follows.
  {documentation}
trend_prompt: |
  We have a plot from repeated simulations of an agent based model.
  Your goal is to describe the trends in details from the plot, mentioning key time steps and values taken by the metric in the plot, and interpreting them based on the context of the model.
  The report must objectively describe the trends in the data without addressing the quality of the simulation.
  Do not refer to the plot or any visual in your description.
  If a plot has very simple dynamics, simply state them without expanding.
  Metric description: {description}
  Context: {context}
coverage_eval_prompt: |
  Your task is to rate a report based on its coverage with respect to an input context and input plots.
  Coverage is on a scale from 1 (worst) to 5 (perfect).
  Your answer must state the number you give for coverage and your reasoning.
  Input context:
  {source}

  Report to rate:
  {summary}

  Return "Coverage score: <1-5>" and brief reasoning.
faithfulness_eval_prompt: |
  Your task is to rate a report based on its faithfulness with respect to an input context and input plots.
  Faithfulness is on a scale from 1 (worst) to 5 (perfect).
  Your answer must state the number you give for faithfulness and your reasoning.
  Input context:
  {source}

  Report to rate:
  {summary}

  Return "Faithfulness score: <1-5>" and brief reasoning.
style_features:
  role: You are an expert in agent-based modeling and statistics.
  insights: Keep interpretation objective and concise.
